name: Daily Report

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Generate daily report
        run: go run handlers/report_generator.go

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Report"
          to: 1751162157@qq.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: "$(cat data/$(date +'%Y%m%d')/daily_report.md)"
